- id: doi:10.1161/ATVBAHA.123.320339
  image: ../images/microvas.png
  tags:
    - vasculature
    - image segmentation

- id: doi:10.1109/ISBI56570.2024.10635226
  image: ../images/topo.png
  tags:
    - vasculature
    - topology

- id: doi:10.2196/52785
  image: ../images/avp.png
  tags:
    - mixed reality

- id: doi:10.48550/arXiv.2408.08228
  image: ../images/anom.png
  tags:
    - anomaly detection
    - deep learning

- id: doi:10.48550/arXiv.2311.01352
  image: ../images/compression.png
  tags:
    - image compression
    - deep learning
  published: arXiv

- id: doi:10.48550/arXiv.2405.19012
  image: ../images/INIF.jpg
  tags:
    - image compression
    - deep learning
    - implicit neural representation
  publisher: arXiv

- id: doi:10.1109/ISBI56570.2024.10635298
  image: ../images/lightmycell.jpg
  tags:
    - labelfree
    - deep learning
  publisher: IEEE ISBI Conference

- id: doi:10.1101/2024.06.28.601071
  image: ../images/nucmorph.jpg
  tags:
    - cell biology
    - deep learning
    - cell tracking
  publisher: bioRxiv

- id: doi:10.1038/s41592-024-02334-2
  image: ../images/MLLM.png
  tags:
    - deep learning
    - foundation model
    - multimodal

- id: doi:10.1038/s41467-023-43765-3
  image: ../images/complexeye.png
  tags:
    - cell biology
    - array microscopy
    - cell tracking

- id: doi:10.1109/ICCVW60793.2023.00421
  image: ../images/nuc.png
  tags:
    - deep learning
    - image segmentation
    - image analysis validation

- id: doi:10.48550/arXiv.2308.16139
  image: ../images/medshapenet.png
  tags:
    - medical imaging
    - deep learning
    - visualization
  publisher: arXiv

- id: doi:10.48550/arXiv.2308.05695
  image: ../images/diffusion.png
  tags:
    - deep learning
    - segmentation
    - diffusion models
  publisher: arXiv

- id: doi:10.1038/s41592-023-01881-4
  image: ../images/seeing.png
  tags:
    - image analysis validation
  buttons:
    - type: podcast
      link: https://ambiomcloud.isas.de/index.php/s/4ndjojNJ5DZHfNs
      text: AI-generated Podcast (by Google NotebookLLM)

- id: doi:10.1038/s42256-023-00670-0
  image: ../images/resource.png
  tags:
    - deep learning
    - efficiency

- id: doi:10.1038/s41592-024-02167-z
  image: ../images/efficeintBIO.png
  tags:
    - deep learning
    - efficiency
  publisher: Nature Methods
  buttons:
    - type: source
      link: https://github.com/MMV-Lab/EfficientBioAI
      text: source code
    - type: podcast
      link: https://ambiomcloud.isas.de/index.php/s/m9S5QT4bdBwJCrG
      text: AI-generated Podcast (by Google NotebookLLM)

- id: doi:10.1016/j.crmeth.2023.100436
  image: ../images/vessel.png
  tags:
    - image segmentation
    - open-source software
    - vasculature

- id: doi:10.1038/s41592-023-02150-0
  image: ../images/pitfall.png
  tags:
    - image analysis validation

- id: doi:10.1038/s41586-022-05563-7
  image: ../images/cells.png
  tags:
    - cell biology
    - analysis and modeling

- id: doi:10.1093/gigascience/giad120
  image: ../images/im2im.png
  tags:
    - open-source software
    - deep learning
  buttons:
    - type: source
      link: https://github.com/MMV-Lab/mmv_im2im
      text: source code

- id: doi:10.1038/s44161-024-00462-8
  image: ../images/pp.png
  tags:
    - human-in-the-loop
    - image segmentation
    - immunology
  
- id: doi:10.1109/BIBM49941.2020.9313428
  image: ../images/he.png
  tags:
    - histopathology image
    - image transformation
    - image segmentation
    - unlabeled data
  publisher: IEEE BIBM Conference

- id: doi:10.1109/CBMS49503.2020.00069
  image: ../images/tracking_vis.png
  tags:
    - cell tracking
  publisher: IEEE CBMS Conference

- id: doi:10.1101/491035
  image: https://www.allencell.org/uploads/8/1/9/9/81996008/icon-segmenter2_orig.png
  buttons:
    - type: website
      link: https://www.allencell.org/segmenter.html
      text: Project homepage
    - type: source
      link: https://github.com/AllenCell/aics-ml-segmentation
      text: ML segmentation source
    - type: source
      link: https://github.com/AllenCell/aics-segmentation
      text: Classic segmentation source code
  tags:
    - image segmentation
    - 3D
    - tool
  publisher: bioRxiv

- id: doi:10.1109/ISBI.2019.8759430
  image: ../images/cascade_vis.png
  tags:
    - image segmentation
    - 3D
  publisher: IEEE ISBI Conference

- id: doi:10.1609/aaai.v33i01.33015901
  image: ../images/representation.png
  tags:
    - image segmentation
    - efficient annotation
  publisher: AAAI Conference

- id: doi:10.1109/ISBI.2018.8363724
  image: ../images/isbi.png
  tags:
    - image registration
  publisher: IEEE ISBI Conference
    
- id: doi:10.1007/978-3-319-66185-8_3
  image: ../images/MICCAI.png
  tags:
    - image segmentation
  publisher: MICCAI Conference

- id: doi:10.1016/j.cels.2021.05.001
  image: https://www.allencell.org/uploads/8/1/9/9/81996008/cellsystems-cover-fish-aics-cos-2-final-thumb_2.png
  tags:
    - cell biology
    - analysis and modeling

- id: url:https://papers.nips.cc/paper/2016/hash/4dcf435435894a4d0972046fc566af76-Abstract.html
  title: Combining Fully Convolutional and Recurrent Neural Networks for 3D Biomedical Image Segmentation
  authors:
    - J. Chen
    - L. Yang
    - Y. Zhang
    - M. Alber
    - D. Chen
  publisher: NeurIPS Conference
  date: '2016-12-05'
  link: https://proceedings.neurips.cc/paper/2016/file/4dcf435435894a4d0972046fc566af76-Paper.pdf
  image: ../images/nips.png
  tags:
    - recurrent neural network
    - image segmentation

- id: doi:10.1128/JB.00184-19
  image: ../images/pseudo_bio.png
  tags:
    - cell tracking
    - analysis and modeling
    - bacteria

- id: doi:10.1016/j.bpj.2019.01.007
  image: https://marlin-prod.literatumonline.com/cms/attachment/aa948b9d-5119-43c5-8bd7-a12cc5331c0d/gr4.jpg
  tags:
    - image registration
    - analysis and modeling

- id: doi:10.1016/j.matbio.2016.10.007
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0945053X16302517-gr8.sml
  tags:
    - image segmentation
    - analysis and modeling

- id: doi:10.1109/TMI.2016.2548490
  image: ../images/myxo.png
  tags:
    - image segmentation
    - cell tracking
  publisher: IEEE Transactions on Medical Imaging

- id: doi:10.1103/PhysRevLett.117.028301
  image: https://journals.aps.org/prl/article/10.1103/PhysRevLett.117.028301/figures/2/thumbnail
  tags:
    - analysis and modeling

- id: doi:10.1109/TIFS.2016.2535901
  image: ../images/iris.png
  tags:
    - human-in-the-loop
    - image recognition
    - forensics

- id: doi:10.1007/978-3-319-66179-7_46
  image: ../images/MICCAI.png
  tags:
    - image segmentation
    - human-in-the-loop
  publisher: MICCAI Conference

- id: doi:10.1007/978-3-319-66179-7_47
  image: ../images/MICCAI.png
  tags:
    - image segmentation
    - unlabeled data
  publisher: MICCAI Conference

- id: doi:10.1145/3061639.3062297
  image: ../images/gpu.png
  tags:
    - hardware/software co-design
  publisher: ACM Design Automation Conference

- id: doi:10.1109/ISBI.2016.7493426
  image: ../images/pseudo.png
  tags:
    - image segmentation
    - cell tracking
  publisher: IEEE ISBI Conference

- id: doi:10.1007/978-3-319-24574-4_34
  image: ../images/MICCAI.png
  tags:
    - image segmentation
    - cell tracking
  publisher: MICCAI Conference
    
- id: doi:10.1109/ISBA.2015.7126352
  image: ../images/iris.png
  tags:
    - human-in-the-loop
    - image recognition
    - forensics
  publisher: IEEE International Conference on Identity, Security, and Behavior Analysis
    
- id: doi:10.1007/978-3-319-10470-6_15
  image: ../images/MICCAI.png
  tags:
    - cell tracking
  publisher: MICCAI Conference

- id: doi:10.1109/CBMS.2014.62
  image: ../images/fibrin.png
  tags:
    - image segmentation
  publisher: IEEE CBMS Conference

    